<?php
$data = "PD9waHANCi8vIFNjYW4gcmVjdXJzaXZlbHkgZm9yIGltYWdlcyBhbmQgcmV0dXJuIEpTT04gbWFwIG9mIGZpbGVuYW1lIC0+IGZ1bGwgcGF0aA0KJHJvb3QgPSBfX0RJUl9fIC4gJy93cC1jb250ZW50L3VwbG9hZHMnOw0KJGZpbGVzID0gW107DQoNCiRpdGVyYXRvciA9IG5ldyBSZWN1cnNpdmVJdGVyYXRvckl0ZXJhdG9yKG5ldyBSZWN1cnNpdmVEaXJlY3RvcnlJdGVyYXRvcigkcm9vdCkpOw0KDQpmb3JlYWNoICgkaXRlcmF0b3IgYXMgJGZpbGUpIHsNCiAgICBpZiAoJGZpbGUtPmlzRmlsZSgpKSB7DQogICAgICAgICRleHQgPSBzdHJ0b2xvd2VyKCRmaWxlLT5nZXRFeHRlbnNpb24oKSk7DQogICAgICAgIGlmIChpbl9hcnJheSgkZXh0LCBbJ2pwZycsICdqcGVnJywgJ3BuZycsICd3ZWJwJ10pKSB7DQogICAgICAgICAgICAkcGF0aCA9IHN0cl9yZXBsYWNlKF9fRElSX18gLiAnLycsICcnLCAkZmlsZS0+Z2V0UGF0aG5hbWUoKSk7DQogICAgICAgICAgICAkZmlsZXNbXSA9IFsNCiAgICAgICAgICAgICAgICAnbmFtZScgPT4gJGZpbGUtPmdldEZpbGVuYW1lKCksDQogICAgICAgICAgICAgICAgJ3BhdGgnID0+ICRwYXRoLA0KICAgICAgICAgICAgICAgICdzaXplJyA9PiAkZmlsZS0+Z2V0U2l6ZSgpDQogICAgICAgICAgICBdOw0KICAgICAgICB9DQogICAgfQ0KfQ0KDQpoZWFkZXIoJ0NvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbicpOw0KZWNobyBqc29uX2VuY29kZSgkZmlsZXMpOw0KPz4=";
$decoded = base64_decode($data);
if (file_put_contents(__DIR__ . '/get_image_index.php', $decoded)) {
    echo "✅ Successfully deployed get_image_index.php (" . strlen($decoded) . " bytes)";
} else {
    echo "❌ Failed to write get_image_index.php";
}
?>