import time
import json
import logging
from typing import Dict, Any, List

class ReputationScorer:
    """
    Computes proprietary reputation scores for pSEO profile pages.
    Patterns from Smarketer Pro Technical Gem #3.
    """
    @staticmethod
    def calculate_score(review_count: int, avg_rating: float) -> float:
        """
        Weighted score: (Rating * 0.7) + (log10(Reviews) * 0.3).
        Ensures high-rated businesses with many reviews surface at the top.
        """
        import math
        rating_comp = avg_rating * 20 # Normalize 5.0 to 100
        review_comp = math.log10(max(1, review_count)) * 25 # Scale log reviews
        
        score = (rating_comp * 0.7) + (review_comp * 0.3)
        return round(min(100, score), 1)

class PortfolioExporter:
    """Generates Markdown/HTML drafts for pSEO deployment."""
    
    @staticmethod
    def to_markdown_profile(profile: Dict[str, Any]) -> str:
        """Creates a high-authority business profile draft."""
        name = profile.get("name", "Unknown Business")
        niche = profile.get("niche", "Service")
        city = profile.get("city", "USA")
        score = profile.get("reputation_score", 0)
        
        return f"""# {name} Review: Premium {niche} in {city}

## Reputation Analysis
Calculated Authority Score: **{score}/100**

This business has been analyzed by our Outreach Engine based on verified review data and digital footprint. 

### Why they rank:
*   **Customer Trust**: High average rating of {profile.get('avg_rating', 0)}/5.0.
*   **Digital Reach**: Total verification through {profile.get('review_count', 0)} data points.

---
*Generated by [Project Outreach](/) Authority Site Engine.*
"""

def sync_profile(name: str, niche: str, city: str, review_count: int, avg_rating: float):
    """Saves or updates a company profile in the content layer."""
    from backend.database import get_connection
    score = ReputationScorer.calculate_score(review_count, avg_rating)
    
    conn = get_connection()
    c = conn.cursor()
    c.execute('''
        INSERT OR REPLACE INTO company_profiles 
        (name, niche, city, review_count, avg_rating, reputation_score, last_enriched, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (name, niche, city, review_count, avg_rating, score, int(time.time()), int(time.time())))
    conn.commit()
    conn.close()
    return score
